track.go

Hi,
I started using your spotify library. Nice and rather complete!
Started using the CurrentUsersTracks function and noticed that the result didn't contain the album of the tracks, which is returned by the spotify web api. Simply adding the Album to the struct makes it available.

Added Album member to SimpleTrack struct

---

search.go
search_test.go

Hi, 
I found this today and started using it but encountered an issue when trying to search with filters in the query string. I think I've tracked down the issue and my before/after testing seems to indicate that the call to `url.QueryEscape` is the issue. I've only lightly tested it (ran `go test` and tried my example).
I added a unit test that fails without this fix, and passes with the fix. I didn't really know how to name it, or where to place it. I can modify that if you'd like. I used your example of Uptown Funk, but used the filter parameter to search for Bruno Mars since he's a featured artist.

Don't escape the query string before calling encode.

---

album.go
page.go
test_data/current_users_albums.txt
user.go
user_test.go

Support for `Get Current User's Saved Albums` endpoint 
https://developer.spotify.com/web-api/get-users-saved-albums/

Support Get Current User's Saved Albums endpoint

---

playlist.go

Fixes a bug in the library that causes in adding tracks to a playlist
currently being non-functional. The library passes "urls", but [as
described in the documentation][doc], it should actually be "uris".
[doc]: https://developer.spotify.com/web-api/console/post-playlist-tracks/#complete

Fix parameter for adding tracks to playlist: should be "uris"

---

album.go
artist.go
playlist.go
spotify.go
track.go
user.go

The current implementation seem to map these collections to a single struct
(the `ExternalURL` type) containing a Key/Value which in practice doesn't
unmarshal to anything. As dictated by the documentation [1], these are simple
objects mapping a string to a string and that's unlikely to change during this
API version, so I'd recommend using a simple map instead (for user
convenience).
The `ExternalURL` seems to be using the special JSON annotations of
`json:"{key}"`, which I would guess are supposed to help unmarshal an object,
but I couldn't find any record of them online (and as noted above, the singular
nature of the resources will prevent a successful unmarshaling anyway, I think
at the very least you'd want `[]ExternalURL`).
Note that `ExternalIDs` have the same problem, but are not …

Fix ExternalURL collections

---

recommendation.go
recommendation_test.go
test_data/recommendations.txt
track_attributes.go

Hi,
Thanks for this library ! Here is a contribution regarding the [Recommendations API](https://developer.spotify.com/web-api/get-recommendations/).
I tried to keep in line with the rest of the code. There are a few things I'd like to point out since they can be discussed :
* The big fat TrackAttributes struct is declared in its own file for better readability, but is only used by recommendations.go.
* Serializing these attributes to url values the usual way would represent a big function checking, for each of the 42 attributes, that it is not nil before inserting it into the url. In favor of code conciseness I opted for reflection instead, see the _setTrackAttributesValues_ function. There might be a small performance hit in doing reflection, that I did not evaluate. If you prefer the …

Add support for recommendations based on seeds

---

audio_features.go

This version uses the track ids passed into the GetAudioFeatures method.

Add track ids to audio features request

---

auth.go
spotify.go

As discussed in #20, oauth2 used HTTP/2 for authenticating the user. Now, the old `auth2.NoContext` has been substituted by `context.Context` and the default `http.Client` has been overrided as stated in the [documentation](https://golang.org/pkg/net/http/#pkg-overview) for using HTTP/1

Change http client of oauth2 to force HTTP/1

---

recommendation.go

Add GetAvailableGenreSeeds() method as per https://developer.spotify.com/web-api/console/get-available-genre-seeds/
I had need of this functionality to populate a list of allowable seed genres for creating playlists based on recommendations.
I haven't added tests for this method, as I'm not sure how to go about comparing the output to a static list, as the output from Spotify may change over time.

Add GetAvailableGenreSeeds() method

---

user.go
user_test.go

When passing something other than the default values to
`CurrentUsersFollowedArtistsOpt`, the client returns an error
like "Invalid type: artist?limit=50".

Fix Invalid Type error in CurrentUsersFollowedArtistsOpt

---

player.go

Currently, `Previous()` calls `NextOpt(nil)` instead of `PreviousOpt(nil)` causing a skip to the next track instead of correctly skipping to the previous track.

Fix Previous() to stop skipping to next track

---

spotify.go
spotify_test.go

Fixes #34. The issue was caused by the WebAPI responding to `NewReleases` with this format: 
Specifically note, `"albums" : {`
```json
{
"albums" : {
"href" : "https://api.spotify.com/v1/browse/new-releases?offset=0&limit=20",
"items" : [ {
"album_type" : "single",
"artists" : [ {
"external_urls" : {
"spotify" : "https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM"
},
"href" : "https://api.spotify.com/v1/artists/2h93pZq0e7k5yf4dywlkpM",
"id" : "2h93pZq0e7k5yf4dywlkpM",
"name" : "Frank Ocean",
"type" : "artist",
"uri" : "spotify:artist:2h93pZq0e7k5yf4dywlkpM"
} ],
"available_markets" : [],
"external_urls" : {
"spotify" : "https://open.spotify.com/album/7yOOPJjNelITCaYMqk8V6r"
},
"href" : "https://api.spotify.com/v1/albums/7yOOPJjNelITCaYMqk8V6r",
"id" : "7yOOPJjNelITCaYMqk8V6r", …
```

Unmarshalling NewReleases response into a map 

---

audio_analysis.go
audio_analysis_test.go
test_data/get_audio_analysis.txt

This PR is an extension of the one opened by @therealpenguin (#31). The commits by @therealpenguin have been rebased against `github.com/zmb3/spotify/master` and then one additional commit was added on top to address some style feedback and make the type names a bit more appealing and to fix some comment issues:
```
commit 5888e41c5d569636fc38789086641e617df328ef
Author: Tim Heckman <t@heckman.io>
Date:   Mon Apr 17 19:43:24 2017 -0700
small style enhancements to Audio Analysis code
* ensure comments on exported types use the format `<Thing>...`
* rename `AudioAnalysisMeta` to `AnalysisMeta`
* rename `AudioAnalysisTrack` to `AnalysisTrack`
Signed-off-by: Tim Heckman <t@heckman.io>
```
I suspect some of what I've done may be considered bikeshedding, so I am happy to close this in-favor of …

Extend PR #31: Add support for Get Audio Analysis

---

README.md
album.go
artist.go
audio_analysis.go
audio_features.go
category.go
library.go
page.go
player.go
playlist.go
recommendation.go
search.go
spotify.go
spotify_test.go
track.go
user.go

The Spotify API imposes rate-limits but this is obscured by the client. I added the ability to enable automatic-retries by the client (this has to be specifically enabled though). Before I did this, I had to refactor all of the requests to use common request mechanisms. These common calls:
1. Use an alternative implementation of `decodeError` that extracts the retry-interval from the headers and sets it into the `Client` struct.
2. Determine if we're to automatically retry, waits the provided amount, and then tries again.
I also added a small thing that sets our error-message to the description for the HTTP error-code if the request failed but the error-message is empty. This was really confusing when I tried to add a bunch of tracks to a playlist and it failed for no clear reason.

Added automatic-retries

---

album.go

Hey, I've recently used this package for a project, and found that I needed the array of artists which the Spotify API returns when searching for albums. Therefore I decided to also create a pull request in case you're interested in implementing this change.

SimpleAlbum with SimpleArtists

---

playlist.go
playlist_test.go

Breaking change to support https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/ 
The idea of introducing alternative paths to be not break the API occurred to me, but it felt like bloating the interface completely. Anyone upgrading to this version should without effort be able to migrate to the new interface.
Fixes https://github.com/zmb3/spotify/issues/77

Change the Playlist API to support user less URIs

---

playlist.go
playlist_test.go

Allow a playlist description to be set. 
This changes the function signature for CreatePlaylistForUser so if we don't want to introduce that breaking change we could drop that and just use ChangePlaylistDescription to modify the description in a subsequent call.
Open to suggestions, thanks
Nate

Allow Playlist description to be added/modified on playlist creation/modification

---

spotify.go

I had only previously checked the issues and not the pull requests, but this is actually a duplicate of https://github.com/zmb3/spotify/pull/81. I do think it would make sense to do this check in Client.get as well as (or instead of) Client.execute, though.

Client.get: on 204, return early

---

auth.go

#94 Added a new showDialog boolean to the `Authenticator` struct and a setter method for it. For now, it is initialized to false by default. I didn't want to break the existing API/flow, so I didn't add it to the constructor or existing configuration methods. I would love any feedback/suggestions/changes as I am not super familiar with Go code bases :)

Add AuthURLWithDialog to force app authentication with Spotify

---

category.go
playlist.go
playlist_test.go
search.go

Misspelled words were caught by the Misspell package of the Go Report Card tool.
Before: https://goreportcard.com/report/github.com/zmb3/spotify#misspell
After: https://goreportcard.com/report/github.com/fgoyer/spotify#misspell

[Minor] Correct Misspellings

---

album.go
audio_features.go

Resolves #101 by moving the `ReleaseDateTime` method to the `SimpleAlbum` struct and removing the unnecessary re-declarations of various fields from the `FullAlbum` struct.

Move ReleaseDateTime method to SimpleAlbum struct

---

auth.go

Hi there, I was trying to use the library with another project and I've found a weird behavior when trying to authenticate against the API using the `UserReadBirthdate` scope. I've spent some time doing a research about the scope, and it is not available anymore in [Spotify's API docs](https://developer.spotify.com/documentation/general/guides/scopes/).
I've also found some issues at oficial Spotify's GitHub repositories and seems that this scope was deprecated.
Also, I didn't changed any test because there are no tests for this file in the library. 
https://github.com/spotify/web-playback-sdk/issues/11#issuecomment-538620631
https://github.com/spotify/web-api/issues/1262#issuecomment-524833983

Remove deprecated UserReadBirthdate

---

spotify.go

Implements the behaviour from #88 for `client.execute()` as well.
This prevents an EOF error when client.execute() receives status 204 (No Content), e.g. when `client.PlayerCurrentlyPlaying()` is called while nothing is playing.
Resolves #109.

Client.execute: Don't return EOF for response status 204

---

playlist.go

This adds support for the `market` parameter in the playlist track listing endpoint, by way of the `Options` object. Several other endpoints read in this way already, such as in [CurrentUserAlbumsOpt](https://github.com/zmb3/spotify/blob/a5be8edef7dec2ea1d671ba883ce9361e7e79f91/user.go#L270).
Some tracks, like [this one](https://open.spotify.com/track/0Ov5RZIZfDD8A2d9nOWUgQ), provide different localized names for the track / album depending on which market the request is being made from. This also when querying playlists that include tracks with localized names.

GetPlaylistTracksOpt should respect Country in Options object

---

artist.go

https://github.com/zmb3/spotify/blob/master/artist.go#L127-L131
I have a use case where I want ALL albums for an artist and then I need to be able to not send the `markets` url-value. 
Edit: ~This is my suggestion on how to do it while keeping the current behaviour where an unspecified market will give you US as default.~
Suggestions for other implementations are welcome 🙏

feat: Enable option to not sent market using GetArtistAlbumsOpt

---

artist.go

This API will be backwards compatible, but also support the full potential of the underlying endpoint. See https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/ for reference

GetArtistAlbumsOpt: Improvements and bug fixes

---

playlist.go

I don't know why error is not been returing in this method, but I think it's useful and let follow and print it anywhere

Returned error in removeTracksFromPlaylist when error occurs

---

spotify.go

This change allows apps to supply a http.Client they already have, rather than relying on the Authenticator helper. An app might use common code to obtain an auth'd http.Client because it interacts with many OAuth services.

Allow client creation from authorizing HTTP client

---

auth.go
examples/authenticate/pkce/pkce.go

This allows for support of the PKCE authentication flow along with any other flows that might require extra URL params on the token or auth URL.

Add optional URL params to URL and Token functions 

---

album.go
album_test.go
track.go
user.go

Thank you for this great lib. 
- The `me/tracks` API uses the `market` query parameter instead of `country`.
- When the `market` query parameter is passed, an `is_playable` and `linked_from` key is returned.
Updating all the API to support track relinking:

Fixing CurrentUsersTracksOpt market query parameter + proper handling of results

---

auth.go

So we can set "code_verifier" param url without needing an
HTTP request.

Add ExchangeWithOpts to be used with pkce authentication

---

player.go

The JSON key for the item object in the CurrentlyPlaying struct is now in lowercase. See [https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-the-users-currently-playing-track](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-the-users-currently-playing-track)

Fix spelling of a JSON key

---

track.go

Add a missing json field in the SimpleTrack struct
https://developer.spotify.com/documentation/web-api/reference/#object-trackobject

Add track type in Track struct

---

playlist.go
playlist_test.go

The collaborative parameter is optional in the Spotify Web API, and was
not supported in this library. I add the parameter to directly to the
CreatePlaylistForUser function, though a case could be made for writing
a separate function in order to avoid breaking existing calls.
Note that I do not check for the relationship between public and
collaborative in the body of the function, instead I let the Web API
return an error.
I added two tests for the private/public-collaborative permutations in
order to demonstrate the intended usage of the fields.

Accept collaborative parameter for CreatePlaylistForUser

---

playlist.go
playlist_test.go

Seems the follower api url is incorrect: https://developer.spotify.com/documentation/web-api/reference/#endpoint-follow-playlist
It does not need an 'owner id'

fix: follow api

---

examples/cli/cli.go

This PR is intended to showcase how this library can be used without having to spin up a web server and instead directly use the auth-code provided by Spotify to negotiate an OAuth Token. This is specially useful when the first part of the process is done in a frontend and the backend only cares about the auth code the frontend provides.

chore: add sample server side package usage

---

playlist.go
playlist_test.go

Implementation of https://developer.spotify.com/documentation/web-api/reference/#/operations/reorder-or-replace-playlists-tracks replace functionality with URI's instead of trackID's

Add ReplacePlaylistItems

---

playlist.go
playlist_test.go
test_data/get_playlist.txt

Follow up of #202, I realized that including the `Description` field in `SimplePlaylist` means it should removed from `FullPlaylist`.
It is very minor, but having it in both structs (In addition to being redundant) means that when explicitly selecting the `SimplePlaylist` part from the struct, the `Description` is always empty. It meant we couldn't do this :
```go
func printDescription(playlist SimplePlaylist) {
fmt.Println(playlist.Description)
}
playlist, err := client.GetPlaylist(ctx, spotify.ID(spotifyID)) // Assume we fetch a playlist with a non empty Description
printDescription(playlist.SimplePlaylist) // Prints nothing, even if playlist.Description is not empty
}
```

fix: description field in FullPlaylist was shadowing the one from SimplePlaylist

---

show.go
show_test.go

This PR adds the SaveShowsForCurrentUser endpoint
https://developer.spotify.com/documentation/web-api/reference/#/operations/save-shows-user

Add SaveShowsForCurrentUser endpoint

---

library.go
library_test.go
player.go

fix: use ctx in modifyLibrary calls

Pass context to modifyLibrary calls

---

spotify.go

Currently, given the use of `time.Sleep`, retry time periods completely ignore the context passed into the function. This PR swaps the sleep logic to instead use a `select` and `time.After`, so that context cancellation will successfully cancel the sleep. The behavior in this PR is just to return the original error if context is cancelled during the retry Sleep. If you'd prefer, I can also swap to return a context cancellation, too.
Signed-off-by: Russell Troxel <russelltroxel@gmail.com>

Allow retry period to be cancelled by context

---

spotify.go

Fixes #182 
In #183 concern was raised that removing `202` responses from `shouldRetry` might lead to breakage elsewhere. This PR takes a slightly different approach, and instead just checking `isFailure` to determine if we have the status we're looking for before deciding if we should retry the request.
Signed-off-by: Russell Troxel <russelltroxel@gmail.com>

[Fix #182] Test success before retrying request

---

player.go

even if spotify docs says its returns HTTP status 204, some endpoints return HTTP status 202

fix: support HTTP status 202

---

player.go

The comment in the code doesn't reflect the repeat states that the Spotify API expects. This PR updates the comment to align with the correct states.

Change incorrect player repeat options

---

player.go

Fixes #219 
https://github.com/zmb3/spotify/commit/9d29507c9a13689c913905f76e69974e8b234072 changed the JSON tag of the PlaybackOffset.Position resulting in it not being ignored when only URI was set. Which lead to the error mentioned #219. This PR fixes this by making PlaybackOffset.Position an integer pointer, hence it won't be ignored when it will be zero and will be ignored when only URI is set.

Make spotify.PlaybackOffset.Position an *int 

---

auth/auth.go

Existing code did not have a mechanism to update access tokens with refresh tokens.
So I added `RefreshToken` method which returns a new access token if it has expired.
```go
ctx := context.Background()
token := getToken() // get an existing token somehow
auth := spotifyauth.New()
newToken, err := auth.RefreshToken(ctx, token) // refresh token here
if err != nil {
fmt.Println(err)
}
if token.AccessToken != newToken.AccessToken {
saveToken(newToken) // save a new token
}
client := spotify.New(auth.Client(ctx, newToken))
```
- #232 
- #221

add RefreshToken method for Authenticator

---

examples/authenticate/pkce/pkce.go

Simple fix for pkce auth example that I stumbled across while trying the library. I'm unsure if this is a a specification requirement for pkce auth as I haven't finished reading the RFC, but if you do not set the client_id as a param, you get a helpful message that it needs to be set. 
This change assumes that the user will provide the client_id as an env var.

fix: add client_id field to pkce auth example.

---

track.go
user_test.go

They're both already present in SimpleTrack, and in the case of ExternalIDs, in a more convenient form.  By putting the duplicate in FullTrack, SimpleTrack is rendered invalid/incomplete (since the json tags on the embedded fields are shadowed), and also use a less useful type (map[string]string, rather than TrackExternalIDs).
This is, of course, a breaking change, and should target v3.

Remove duplicate Album and ExternalIDs fields from FullTrack

---

spotify.go

~It may be a better idea simply to remove this constant, as it's not referenced anywhere internally, and clearly hasn't been updated in long time, so it seems unlikely anybody is using it for anything valuable.  And v3 is a nice time to remove unused things.~
Remove woefully outdated Version constant

Remove the Version constant

---

spotify.go
spotify_test.go

Related to, and useful along with #273

Expose RetryAfter value in error

---

category_test.go
playlist_test.go
spotify.go
spotify_test.go

Today's Spotify outage, and the plethora of random errors it's causing my service to return, inspired me to make errors a bit more parseable.
This PR does two things:
- It adds a convenience `HTTPStatus() int` method on the custom `spotify.Error` type, as an easy way to convient the HTTP status.
- It ensures that all errors actually include said HTTP status, when it's available.
It also changes the wording of some errors, for consistency, which may break some consumers of this library, if they depend on error string matching, which this PR will help make less necessary.

More consistently include the HTTP response code in errors
