zmb3/spotify

- playlist.go
- playlist_test.go
> user id should be a string in ReorderPlaylistTracks

- auth.go
- examples/authenticate/authenticate.go
On NewClient, in case of ExpiredToken, regenerate a new Token and update the current Token
> update Token on NewClient

- auth.go
- examples/player/player.go
- player.go
- player_test.go
- test_data/player_available_devices.txt
- test_data/player_currently_playing.txt
- test_data/player_state.txt
See: https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/
Still needs some tests, more than willing to take feedback on naming or whatever.
> Initial work to add Web API Connect Endpoint

- player.go
> Fix TransferPlayback to only take a single ID

- spotify.go
> Simplified NewReleasesOpt.

- auth.go
- player.go
- player_test.go
- test_data/player_recently_played.txt
- track.go
Also added String() to `SimpleTrack`.
> Added get-recently-played to player.

- playlist.go
Sending the URIs for the AddTracksToPlaylist function as body rather than query paramater improves performance when sending a large number of tracks (around 50-80 ish)
> A maximum of 100 tracks can be added in one request. Note: it is likely that passing a large number of track URIs as a query parameter will exceed the maximum length of the request URI. When adding a large number of tracks it is recommended to pass them in the request body
(https://developer.spotify.com/web-api/add-tracks-to-playlist/ )
> AddTracksToPlaylist POST URIs as body rather than query parameter

- auth.go
- spotify.go
- test_data/current_users_top_artists.txt
- test_data/current_users_top_tracks.txt
- user.go
- user_test.go
Fulfills #48 with two new functions along with respective unit tests.
> Add Current User's Top Artists/Tracks Functionality

- user.go
Added the ability to specify an offset when obtaining the top tracks of a current user.
> Added offset to toptracks

- player_test.go
- spotify.go
Fixes #99
Sorry to snipe pull #100
> Update execute to accept any 2XX as success

- artist.go
> Bug: Added json-tag to FullArtist.Followers

- page.go
- show.go
- user.go
Added support for user's saved shows (podcasts)
> added: CurrentUsersShows(), CurrentUsersShowsOpt()

- spotify.go
> Enable to set Accept-Language header in HTTP GET request

- page.go
- show.go
- show_test.go
- test_data/get_show.txt
- test_data/get_show_episodes.txt
Add support for [GetShow](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-a-show) and [GetShowEpisodes](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-a-shows-episodes) APIs.
```go test -v``` passes.
> changes to support GetShow, GetShowEpisodes

- library.go
- library_test.go
Add context and slight code-reuse
> fix: library albums v2

- spotify.go
- spotify_test.go
Hi, this should resolve Issue #169.
@strideynet
> feat: add method to get the current OAuth token from client

- auth/auth.go
Setting a custom Transport with no ability for the caller to configure
it breaks the ability to configure an http proxy, while the default
behavior via http.DefaultTransport is to support it (via env),
see https://pkg.go.dev/net/http#RoundTripper.
This was added because Spotify didn't support HTTP/2 in 2017, but it
does now. Also, Go net/http should auto negotiate better.
> auth: remove contextwithHTTPClient

- .gitignore
- README.md
- examples/paging/page.go
- playlist.go
> Fix local tracks in GetPlaylistItems

- player.go
- player_test.go
- test_data/get_queue.txt
I added the function "GetQueue" that pulls the users queue from the new Endpoint:
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-queue
> Adding "GetQueue" Function to player.go.

- examples/features/features.go
an example that illustrates retrieving song features from an album
> add features example

- album.go
> Add TotalTracks to SimpleAlbum struct

- category.go
- library.go
- player.go
- playlist.go
- playlist_test.go
- spotify.go
- user.go
- Stop using deprecated `io/ioutil` package
- Remove a redundant nil slice check
- Remove redundant error nil checking
> Misc minor cleanups
